#!/bin/sh

# We reinstalled the systemd unit file, so even though it may not have changed,
# tell systemd to reload
systemctl daemon-reload

systemctl enable --now mnt_reform_keyboard_backlight_rainbow
